name: Testing with Pytest
run-name: Pytest

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests and generate XML report
        run: python -m pytest --junitxml=pytest-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: pytest-report.xml

      - name: Notify on success
        if: success()
        run: echo "Tests passed successfully"

      - name: Notify on failure
        if: failure()
        run: echo "Tests failed"
